services:
  configserver:
    image: hyness/spring-cloud-config-server:latest
    container_name: discord-bots-configserver
    restart: always
    networks:
     - discord-bots
    ports:
     - "6969:6969"
    volumes:
     - ./configserver:/config
    environment:
     JAVA_OPTS: "-Dspring.profiles.active=native -Dspring.cloud.config.server.native.searchLocations=file:/config -Dserver.port=6969 -Dserver.ssl.enabled=false"
  postgres:
    image: postgres:latest
    container_name: discord-bots-postgres
    restart: always
    volumes:
     - ./postgres-data:/var/lib/postgresql/data/
    networks:
     - discord-bots
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=admin
    healthcheck:
     test: [ "CMD-SHELL", "pg_isready" ]
     interval: 30s
     timeout: 60s
     retries: 5
     start_period: 30s
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: discord-bots-pgadmin
    restart: always
    volumes:
     - ./pgadmin-data:/var/lib/pgadmin
    networks:
     - discord-bots
    depends_on:
     postgres:
      condition: service_healthy
    ports:
     - "2345:80"
    environment:
     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
     - PGADMIN_DEFAULT_PASSWORD=admin
  vchelper:
    image: ericasoft/ericasoft-discord-vchelper:latest
    container_name: discord-bots-vchelper
    restart: always
    depends_on:
     postgres:
      condition: service_healthy
    networks:
     - discord-bots
    ports:
     - 42069:42069
networks:
  discord-bots: